"""create outbox table

Revision ID: 5bfab7e344e7
Revises: e043316ceb81
Create Date: 2026-01-12 13:51:56.121405

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5bfab7e344e7'
down_revision: Union[str, Sequence[str], None] = 'e043316ceb81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'outbox',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            'aggregate_type',
            sa.String(),
            nullable=False,
            comment='Тип агрегата (например: order)',
        ),
        sa.Column(
            'aggregate_id',
            sa.BigInteger(),
            nullable=False,
            comment='ID агрегата (order_id)',
        ),
        sa.Column(
            'event_type',
            sa.String(),
            nullable=False,
            comment='Тип события (например: OrderCreated)',
        ),
        sa.Column(
            'payload',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment='JSON payload события',
        ),
        sa.Column(
            'status',
            sa.Enum('NEW', 'SENT', 'ERROR', name='outbox_status'),
            nullable=False,
        ),
        sa.Column(
            'attempts',
            sa.Integer(),
            nullable=False,
            comment='Количество попыток отправки',
        ),
        sa.Column(
            'next_retry_at',
            sa.DateTime(timezone=True),
            nullable=True,
            comment='Дата следующей попытки отправки',
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'last_error',
            sa.Text(),
            nullable=True,
            comment='Последняя ошибка при отправке',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_outbox_aggregate_id'),
        'outbox',
        ['aggregate_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_outbox_aggregate_type'),
        'outbox',
        ['aggregate_type'],
        unique=False,
    )
    op.create_index(
        op.f('ix_outbox_event_type'), 'outbox', ['event_type'], unique=False
    )
    op.create_index(
        op.f('ix_outbox_status'), 'outbox', ['status'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_status'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_event_type'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_aggregate_type'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_aggregate_id'), table_name='outbox')
    op.drop_table('outbox')
    # Без этого тип остаётся в БД и повторный upgrade падает на CREATE TYPE.
    op.execute('DROP TYPE IF EXISTS outbox_status')
