"""Create orders tables

Revision ID: d1f66ccd60bc
Revises:
Create Date: 2026-01-01 15:06:25.985776

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd1f66ccd60bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'user_id',
            sa.Integer(),
            nullable=False,
            comment='ID пользователя (владелец заказа)',
        ),
        sa.Column(
            'status',
            sa.String(length=32),
            nullable=False,
            comment='Статус заказа',
        ),
        sa.Column(
            'total_price',
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment='Итоговая стоимость заказа',
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
            comment='Дата создания заказа',
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
            comment='Дата последнего обновления заказа',
        ),
        sa.CheckConstraint(
            'total_price >= 0', name='ck_orders_total_price_non_negative'
        ),
        sa.CheckConstraint('user_id >= 1', name='ck_orders_user_id_positive'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_orders_status'), 'orders', ['status'], unique=False
    )
    op.create_index(
        op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
