"""alter orders.user_id to bigint

Revision ID: e043316ceb81
Revises: 9377a7524d09
Create Date: 2026-01-05 18:14:06.731072

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e043316ceb81'
down_revision: Union[str, Sequence[str], None] = '9377a7524d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'orders',
        'user_id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        comment=None,
        existing_comment='ID пользователя (владелец заказа)',
        existing_nullable=False,
    )
    op.alter_column(
        'orders',
        'status',
        existing_type=postgresql.ENUM(
            'PENDING', 'CONFIRMED', 'CANCELLED', name='order_status'
        ),
        comment=None,
        existing_comment='Статус заказа',
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'orders',
        'status',
        existing_type=postgresql.ENUM(
            'PENDING', 'CONFIRMED', 'CANCELLED', name='order_status'
        ),
        comment='Статус заказа',
        existing_nullable=False,
    )
    op.alter_column(
        'orders',
        'user_id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        comment='ID пользователя (владелец заказа)',
        existing_nullable=False,
    )
    # ### end Alembic commands ###
