[project]
name = "microservices-notification"
version = "0.1.0"
description = "Микросервис notification"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ms-events",
    "aiokafka>=0.13.0",
    "aiosmtplib>=3.0.2",
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "fastapi",
    "greenlet>=3.3.0",
    "prometheus-client>=0.23.1",
    "prometheus-fastapi-instrumentator>=7.1.0",
    "psycopg2-binary>=2.9.11",
    "pydantic>=2.0",
    "pydantic-settings",
    "sqlalchemy>=2.0.45",
    "structlog>=25.5.0",
    "uvicorn[standard]>=0.38.0",
]

[tool.uv]
package = false

[dependency-groups]
dev = [
    "ruff>=0.14.9",
]
