import re

LOGIN_MIN_LENGTH = 3
LOGIN_MAX_LENGTH = 30
NAME_MAX_LENGTH = 255
USERNAME_RE = re.compile(r'^[a-z0-9_.-]+$')

FULL_NAME_MIN_LENGTH = 1
FULL_NAME_MAX_LENGTH = 100

PASSWORD_MIN_LENGTH = 1
PASSWORD_MAX_LENGTH = 128
