"""create orders_history table

Revision ID: 336334812c27
Revises:
Create Date: 2026-01-07 17:17:13.332495

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '336334812c27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'order_history',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('order_id', sa.BigInteger(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('event_id', sa.String(length=64), nullable=False),
        sa.Column('event_type', sa.String(length=64), nullable=False),
        sa.Column('payload', sa.JSON(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('event_id', name='uq_order_history_event_id'),
    )
    op.create_index(
        op.f('ix_order_history_order_id'),
        'order_history',
        ['order_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_order_history_user_id'),
        'order_history',
        ['user_id'],
        unique=False,
    )
    op.create_table(
        'processed_event',
        sa.Column('event_id', sa.String(length=64), nullable=False),
        sa.Column(
            'processed_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('event_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_event')
    op.drop_index(op.f('ix_order_history_user_id'), table_name='order_history')
    op.drop_index(
        op.f('ix_order_history_order_id'), table_name='order_history'
    )
    op.drop_table('order_history')
    # ### end Alembic commands ###
